# Generated by Django 4.2.7 on 2023-11-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0007_song_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
