# Generated by Django 4.2.7 on 2023-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0010_alter_song_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('watchlater_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
