# Generated by Django 4.2.7 on 2023-11-22 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicbeats', '0012_watchlater_song_watchlater_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('Favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WatchLater',
        ),
    ]
