# Generated by Django 4.2.7 on 2023-11-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0013_favourite_delete_watchlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='credit',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
