# Generated by Django 4.2.7 on 2023-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0015_alter_song_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='credit',
            field=models.CharField(default='No one', max_length=5000),
        ),
    ]
