# Generated by Django 4.2.7 on 2023-11-23 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicbeats', '0016_alter_song_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('History_id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
